### ISSUE TITLE
Some bugs you may need to fix

### ISSUE THREAD

**Issue by DerrickXuNu** [S-aiueo32/lpips-pytorch#1]
Thanks first for providing this convenient code to use! However, I believe your codes have some potential bugs that needs to be fixed.
1)  If the input data is a cuda tensor, your code will output an error because the pretrained network models is not on the cuda by default.
2)  The Basemodel's mean and std are not set to the same device of the input tensor. If the input is on cuda, then it will throw an error.
3) The linear model url you provided is invalid. Suggest: download the weights from origin author and put to your folder locally so it doesn't need to download anymore.

**Comment by S-aiueo32** [comment]
@DerrickXuNu Thank you for the points.

1. This issue won't be happened. Submodules are put on the same device to the root module in PyTorch.
2. This won't be also happened, because mean and std are defined as buffer, it will be track the same device as said in above.
3. The URL is still valid now, please access [here](https://raw.githubusercontent.com/richzhang/PerceptualSimilarity/master/models/weights/v0.1/alex.pth). I worry about the copyrights, however, putting the weights locally is the simplest way. Additionally, it will improves the performance by reducing the weights downloading. But... functional calls are not recommended, since the weights are read out every time they are executed anyway.

**Comment by GitCVfb** [comment]
Hello, the linear model url you provided is invalid (https://raw.githubusercontent.com/richzhang/PerceptualSimilarity/master/lpips/weights/v0.1/alex.pth). What should I do? Thanks!
